# secrets-reader.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-secrets-sa
  namespace: tridorian-ztna
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tridorian-ztna
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: tridorian-ztna 
subjects:
- kind: ServiceAccount
  name: gke-secrets-sa
  namespace: tridorian-ztna
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
