---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: ztna-secrets
  namespace: tridorian-ztna
spec:
  serviceAccountName: gke-secrets-sa
  secretProviderClassName: ztna-secrets
  secretObject:
    type: Opaque
    data:
      -   sourcePath: "private-key"
          targetKey: "private-key"
      -   sourcePath: "public-key"
          targetKey: "public-key"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: database-secrets
  namespace: tridorian-ztna
spec:
  serviceAccountName: gke-secrets-sa
  secretProviderClassName: database-secrets
  secretObject:
    type: Opaque
    data:
      -   sourcePath: "username"
          targetKey: "username"
      -   sourcePath: "password"
          targetKey: "password"
      -   sourcePath: "database"
          targetKey: "database"
      -   sourcePath: "host"
          targetKey: "host"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: cache-secrets
  namespace: tridorian-ztna
spec:
  serviceAccountName: gke-secrets-sa
  secretProviderClassName: cache-secrets
  secretObject:
    type: Opaque
    data:
      -   sourcePath: "password"
          targetKey: "password"