apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tridorian-ztna

resources:
- ../../deployment

patches:
- path: replicas-patch.yaml

images:
- name: asia-southeast1-docker.pkg.dev/trivpn-demo-prj/triztna/management-api
  newTag: latest
- name: asia-southeast1-docker.pkg.dev/trivpn-demo-prj/triztna/gateway-controlplane
  newTag: latest
- name: asia-southeast1-docker.pkg.dev/trivpn-demo-prj/triztna/auth-api
  newTag: latest
- name: asia-southeast1-docker.pkg.dev/trivpn-demo-prj/triztna/tenant-admin
  newTag: latest
- name: asia-southeast1-docker.pkg.dev/trivpn-demo-prj/triztna/backoffice
  newTag: latest

commonLabels:
  environment: production
