apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- configmap.yaml
- management-api.yaml
- gateway-controlplane.yaml
- auth-api.yaml
- frontend.yaml
- cache.yaml

commonLabels:
  app.kubernetes.io/part-of: tridorian-ztna
  app.kubernetes.io/managed-by: kustomize
