apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gateway-controlplane-route
  namespace: tridorian-ztna
  labels:
    app: gateway-controlplane
spec:
  parentRefs:
  - name: tridorian-ztna-gateway
    sectionName: https
  hostnames:
  - "gwapi.triztna.redev.cloud"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /gateway.v1.GatewayService/
    backendRefs:
    - name: gateway-controlplane
      port: 5443
      weight: 100
